// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notely.Repository.DbContexts;

#nullable disable

namespace Notely.Repository.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20240513080908_Added User Table")]
    partial class AddedUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Notely.Models.Entities.Notes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Home",
                            Description = "Embark on an adventure through the untamed wilderness and discover hidden treasures.",
                            Title = "Exploring the Wilderness"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Business",
                            Description = "Unleash the full potential of your business and witness unprecedented growth and success.",
                            Title = "Unleashing Business Potential"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Personal",
                            Description = "Embark on a transformative journey of self-discovery and unlock your true potential.",
                            Title = "Journey to Self-Discovery"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Home",
                            Description = "Transform your house into a cozy sanctuary where warmth and comfort embrace you.",
                            Title = "Creating a Cozy Home"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Business",
                            Description = "Explore innovative strategies that will revolutionize your business and leave your competitors in awe.",
                            Title = "Innovative Business Strategies"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Personal",
                            Description = "Embrace personal growth and witness the incredible transformation that unfolds within you.",
                            Title = "Embracing Personal Growth"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Home",
                            Description = "Experience the joy and comfort of a home that radiates warmth and love.",
                            Title = "Home Sweet Home"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Business",
                            Description = "Master the art of business and become a visionary leader in your industry.",
                            Title = "Business Mastery"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Personal",
                            Description = "Unleash your inner potential and embark on a journey of self-discovery and personal growth.",
                            Title = "Unleashing Inner Potential"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Home",
                            Description = "Create a serene haven where tranquility and peace envelop your senses.",
                            Title = "Creating a Serene Haven"
                        });
                });

            modelBuilder.Entity("Notely.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28dbccb9-c9fe-43b9-960a-cd21ea66902f"),
                            FirstName = "Bhanuteja",
                            LastName = "Chintha",
                            Password = "Password",
                            Username = "bhanuteja917"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
